version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: grievance-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grievance_auth
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - grievance-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: grievance-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - grievance-network

volumes:
  mysql-data:

networks:
  grievance-network:
    driver: bridge
